// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: pb/api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessStatus_State int32

const (
	ProcessStatus_STARTED ProcessStatus_State = 0
	ProcessStatus_STOPPED ProcessStatus_State = 1
	ProcessStatus_EXITED  ProcessStatus_State = 2
)

// Enum value maps for ProcessStatus_State.
var (
	ProcessStatus_State_name = map[int32]string{
		0: "STARTED",
		1: "STOPPED",
		2: "EXITED",
	}
	ProcessStatus_State_value = map[string]int32{
		"STARTED": 0,
		"STOPPED": 1,
		"EXITED":  2,
	}
)

func (x ProcessStatus_State) Enum() *ProcessStatus_State {
	p := new(ProcessStatus_State)
	*p = x
	return p
}

func (x ProcessStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_api_proto_enumTypes[0].Descriptor()
}

func (ProcessStatus_State) Type() protoreflect.EnumType {
	return &file_pb_api_proto_enumTypes[0]
}

func (x ProcessStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessStatus_State.Descriptor instead.
func (ProcessStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_pb_api_proto_rawDescGZIP(), []int{3, 0}
}

type ResourceLimits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoryInMib   uint32 `protobuf:"varint,1,opt,name=memory_in_mib,json=memoryInMib,proto3" json:"memory_in_mib,omitempty"`
	CpuMillicores uint32 `protobuf:"varint,2,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	DiskReadMbps  uint32 `protobuf:"varint,3,opt,name=disk_read_mbps,json=diskReadMbps,proto3" json:"disk_read_mbps,omitempty"`
	DiskWriteMbps uint32 `protobuf:"varint,4,opt,name=disk_write_mbps,json=diskWriteMbps,proto3" json:"disk_write_mbps,omitempty"`
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_pb_api_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceLimits) GetMemoryInMib() uint32 {
	if x != nil {
		return x.MemoryInMib
	}
	return 0
}

func (x *ResourceLimits) GetCpuMillicores() uint32 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *ResourceLimits) GetDiskReadMbps() uint32 {
	if x != nil {
		return x.DiskReadMbps
	}
	return 0
}

func (x *ResourceLimits) GetDiskWriteMbps() uint32 {
	if x != nil {
		return x.DiskWriteMbps
	}
	return 0
}

type LaunchConfiguration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string          `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string        `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Limits  *ResourceLimits `protobuf:"bytes,3,opt,name=limits,proto3" json:"limits,omitempty"`
}

func (x *LaunchConfiguration) Reset() {
	*x = LaunchConfiguration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LaunchConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchConfiguration) ProtoMessage() {}

func (x *LaunchConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchConfiguration.ProtoReflect.Descriptor instead.
func (*LaunchConfiguration) Descriptor() ([]byte, []int) {
	return file_pb_api_proto_rawDescGZIP(), []int{1}
}

func (x *LaunchConfiguration) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *LaunchConfiguration) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *LaunchConfiguration) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type OutputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *ProcessHandle `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Stream bool           `protobuf:"varint,2,opt,name=stream,proto3" json:"stream,omitempty"`
}

func (x *OutputRequest) Reset() {
	*x = OutputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputRequest) ProtoMessage() {}

func (x *OutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputRequest.ProtoReflect.Descriptor instead.
func (*OutputRequest) Descriptor() ([]byte, []int) {
	return file_pb_api_proto_rawDescGZIP(), []int{2}
}

func (x *OutputRequest) GetId() *ProcessHandle {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *OutputRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type ProcessStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State     ProcessStatus_State `protobuf:"varint,1,opt,name=state,proto3,enum=ProcessStatus_State" json:"state,omitempty"`
	ExitCode  int32               `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ExitError string              `protobuf:"bytes,3,opt,name=exit_error,json=exitError,proto3" json:"exit_error,omitempty"`
}

func (x *ProcessStatus) Reset() {
	*x = ProcessStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStatus) ProtoMessage() {}

func (x *ProcessStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStatus.ProtoReflect.Descriptor instead.
func (*ProcessStatus) Descriptor() ([]byte, []int) {
	return file_pb_api_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessStatus) GetState() ProcessStatus_State {
	if x != nil {
		return x.State
	}
	return ProcessStatus_STARTED
}

func (x *ProcessStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ProcessStatus) GetExitError() string {
	if x != nil {
		return x.ExitError
	}
	return ""
}

type ProcessHandle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ProcessHandle) Reset() {
	*x = ProcessHandle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessHandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessHandle) ProtoMessage() {}

func (x *ProcessHandle) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessHandle.ProtoReflect.Descriptor instead.
func (*ProcessHandle) Descriptor() ([]byte, []int) {
	return file_pb_api_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessHandle) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProcessOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ProcessOutput) Reset() {
	*x = ProcessOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOutput) ProtoMessage() {}

func (x *ProcessOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOutput.ProtoReflect.Descriptor instead.
func (*ProcessOutput) Descriptor() ([]byte, []int) {
	return file_pb_api_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessOutput) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_pb_api_proto protoreflect.FileDescriptor

var file_pb_api_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x01, 0x0a, 0x0e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x22,
	0x0a, 0x0d, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x6e, 0x5f, 0x6d, 0x69, 0x62, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x4d,
	0x69, 0x62, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x70, 0x75, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x70, 0x75, 0x4d,
	0x69, 0x6c, 0x6c, 0x69, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x64, 0x69, 0x73,
	0x6b, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6d, 0x62, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x62, 0x70, 0x73, 0x12,
	0x26, 0x0a, 0x0f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x5f, 0x6d, 0x62,
	0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x6b, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x4d, 0x62, 0x70, 0x73, 0x22, 0x6c, 0x0a, 0x13, 0x4c, 0x61, 0x75, 0x6e, 0x63,
	0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x27, 0x0a, 0x06,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x52, 0x06, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x73, 0x22, 0x47, 0x0a, 0x0d, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0xa6,
	0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x14, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x69,
	0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x78, 0x69, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2d, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x45,
	0x58, 0x49, 0x54, 0x45, 0x44, 0x10, 0x02, 0x22, 0x25, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25,
	0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xfa, 0x01, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x14, 0x2e, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x04, 0x53, 0x74, 0x6f,
	0x70, 0x12, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x1a, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x0e, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0e, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2b, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0e,
	0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e,
	0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x73, 0x2d, 0x6c, 0x69, 0x74, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_api_proto_rawDescOnce sync.Once
	file_pb_api_proto_rawDescData = file_pb_api_proto_rawDesc
)

func file_pb_api_proto_rawDescGZIP() []byte {
	file_pb_api_proto_rawDescOnce.Do(func() {
		file_pb_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_api_proto_rawDescData)
	})
	return file_pb_api_proto_rawDescData
}

var file_pb_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_api_proto_goTypes = []interface{}{
	(ProcessStatus_State)(0),    // 0: ProcessStatus.State
	(*ResourceLimits)(nil),      // 1: ResourceLimits
	(*LaunchConfiguration)(nil), // 2: LaunchConfiguration
	(*OutputRequest)(nil),       // 3: OutputRequest
	(*ProcessStatus)(nil),       // 4: ProcessStatus
	(*ProcessHandle)(nil),       // 5: ProcessHandle
	(*ProcessOutput)(nil),       // 6: ProcessOutput
	(*emptypb.Empty)(nil),       // 7: google.protobuf.Empty
}
var file_pb_api_proto_depIdxs = []int32{
	1, // 0: LaunchConfiguration.limits:type_name -> ResourceLimits
	5, // 1: OutputRequest.id:type_name -> ProcessHandle
	0, // 2: ProcessStatus.state:type_name -> ProcessStatus.State
	2, // 3: WorkerService.Create:input_type -> LaunchConfiguration
	5, // 4: WorkerService.Stop:input_type -> ProcessHandle
	5, // 5: WorkerService.Status:input_type -> ProcessHandle
	3, // 6: WorkerService.Output:input_type -> OutputRequest
	3, // 7: WorkerService.Error:input_type -> OutputRequest
	5, // 8: WorkerService.Create:output_type -> ProcessHandle
	7, // 9: WorkerService.Stop:output_type -> google.protobuf.Empty
	4, // 10: WorkerService.Status:output_type -> ProcessStatus
	6, // 11: WorkerService.Output:output_type -> ProcessOutput
	6, // 12: WorkerService.Error:output_type -> ProcessOutput
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_api_proto_init() }
func file_pb_api_proto_init() {
	if File_pb_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceLimits); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LaunchConfiguration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutputRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessHandle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_api_proto_goTypes,
		DependencyIndexes: file_pb_api_proto_depIdxs,
		EnumInfos:         file_pb_api_proto_enumTypes,
		MessageInfos:      file_pb_api_proto_msgTypes,
	}.Build()
	File_pb_api_proto = out.File
	file_pb_api_proto_rawDesc = nil
	file_pb_api_proto_goTypes = nil
	file_pb_api_proto_depIdxs = nil
}
